# Generated by Django 6.0.3 on 2026-03-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField()),
                ('parent_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.IntegerField()),
                ('thumbnail_image', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_1', models.CharField(max_length=200)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(max_length=200)),
                ('option_4', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprehension_score', models.IntegerField(default=0)),
                ('visual_score', models.IntegerField(default=0)),
                ('spelling_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('total_possible', models.IntegerField(default=0)),
                ('stars_earned', models.IntegerField(default=0)),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='api.child')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('english_audio', models.CharField(blank=True, max_length=300)),
                ('isizulu_audio', models.CharField(blank=True, max_length=300)),
                ('isizulu_word', models.CharField(blank=True, max_length=200)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_words', to='api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='SpellingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('fill-missing-vowel', 'Fill Missing Vowel'), ('drag-letters', 'Drag Letters'), ('copy-writing', 'Copy Writing')], max_length=50)),
                ('display_text', models.CharField(blank=True, max_length=300)),
                ('answer', models.CharField(max_length=300)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_activities', to='api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('text', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('audio_url', models.CharField(blank=True, max_length=300)),
                ('highlighted_words', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.lesson')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='VisualActivityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('correct_word', models.CharField(max_length=100)),
                ('word_options', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_items', to='api.lesson')),
            ],
        ),
    ]
