# Generated by Django 6.0.3 on 2026-05-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailverificationcode_parent_email_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email_verified',
        ),
    ]
