# Generated by Django 6.0.3 on 2026-05-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_emailverificationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.FileField(blank=True, upload_to='child_photos/'),
        ),
        migrations.AddField(
            model_name='child',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_email',
            field=models.EmailField(max_length=254),
        ),
    ]
