# Generated by Django 6.0.3 on 2026-05-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_grade4_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionquestion',
            name='stop_point_text',
            field=models.TextField(help_text='The story line after which the question appears.'),
        ),
    ]
