# Generated by Django 6.0.3 on 2026-08-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True or false'), ('open_ended', 'Open-ended response'), ('sequencing', 'Sequencing'), ('matching', 'Matching'), ('cloze', 'Fill in the blank'), ('oral_response', 'Oral response'), ('prediction', 'Prediction'), ('reasoning', 'Reasoning')], max_length=30)),
                ('skill', models.CharField(choices=[('literal_comprehension', 'Literal comprehension'), ('sequencing', 'Sequencing'), ('inference', 'Inference'), ('vocabulary_in_context', 'Vocabulary in context'), ('prediction', 'Prediction'), ('summarising', 'Summarising'), ('character_motivation', 'Character motivation'), ('text_to_self', 'Text-to-self connection'), ('fact_vs_opinion', 'Fact versus opinion')], max_length=40)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField(blank=True)),
                ('items_in_correct_order', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_activities', to='api.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
