# Generated by Django 6.0.3 on 2026-08-08 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dynamic_assessment_reporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingActivityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_responses', to='api.readingactivity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_responses', to='api.child')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_responses', to='api.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child', 'lesson'), name='unique_child_lesson_reading_response')],
            },
        ),
    ]
