# Generated by Django 6.0.7 on 2026-07-24 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_packagecode_family_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='curriculum_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lesson',
            name='generated_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lessons', to='api.child'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source_attribution',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AIStoryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_story_jobs', to='api.child')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_story_job', to='api.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
