# Generated by Django 6.0.7 on 2026-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ai_story_fields_and_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
