# Generated by Django 6.0.3 on 2026-08-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_readingactivityresponse'),
        ('api', '0016_child_date_of_birth'),
    ]

    operations = [
    ]
