# Generated by Django 6.0.3 on 2026-08-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260809_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='grade_confirmed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('repeated', models.BooleanField(default=False)),
                ('confirmed_by', models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('registration', 'Set at registration')], max_length=20)),
                ('confirmed_by_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='api.child')),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('child', 'year'), name='unique_child_grade_year')],
            },
        ),
    ]
