# Generated by Django 6.0.3 on 2026-09-09 09:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260809_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AccountActionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reactivate_parent', 'Reactivate parent account')], max_length=32)),
                ('code_hash', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_action_otps', to='api.parent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
