# Generated by Django 6.0.3 on 2026-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_child_grade_confirmed_year_gradehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='grade_reminder_sent_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
