# Generated by Django 6.0.3 on 2026-09-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_parent_auth_version_parent_deactivated_at_and_more'),
        ('api', '0019_child_grade_reminder_sent_year'),
    ]

    operations = [
    ]
