# Generated by Django 6.0.3 on 2026-09-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_child_paused_activities'),
        ('api', '0020_merge_20260909_1720'),
    ]

    operations = [
    ]
