# Generated by Django 6.1.1 on 2026-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20260917_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellingactivity',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
