# Generated by Django 6.0.3 on 2026-09-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20260916_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactionotp',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_action_otps', to='api.teacher'),
        ),
        migrations.AddField(
            model_name='child',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='deactivated_reason',
            field=models.CharField(blank=True, choices=[('parent_cascade', 'Parent account deactivated'), ('manual', 'Deactivated individually')], max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='needs_new_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountactionotp',
            name='action',
            field=models.CharField(choices=[('reactivate_parent', 'Reactivate parent account'), ('reactivate_teacher', 'Reactivate teacher account')], max_length=32),
        ),
        migrations.AlterField(
            model_name='accountactionotp',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_action_otps', to='api.parent'),
        ),
    ]
