# Generated by Django 6.0.3 on 2026-09-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20260915_1418'),
        ('api', '0022_accountactionotp_teacher_child_deactivated_at_and_more'),
    ]

    operations = [
    ]
