# Generated by Django 6.0.3 on 2026-09-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_spellingactivity_image_url'),
        ('api', '0023_merge_20260918_2158'),
    ]

    operations = [
    ]
