# Generated by Django 6.0.3 on 2026-09-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20260918_0930'),
        ('api', '0024_merge_20260922_0029'),
    ]

    operations = [
    ]
