# Generated by Django 6.0.3 on 2026-09-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_grade_confirmation_and_paused_activities'),
        ('api', '0024_merge_20260922_0029'),
    ]

    operations = [
    ]
