# Generated by Django 6.0.3 on 2026-09-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20260923_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='extra_active_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='child',
            name='deactivated_reason',
            field=models.CharField(blank=True, choices=[('parent_cascade', 'Parent account deactivated'), ('manual', 'Deactivated individually'), ('plan_capacity', "Over the plan's active-learner limit")], max_length=20),
        ),
    ]
