# Generated by Django 6.0.3 on 2026-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_subscription_extra_active_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_seat_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
