# Generated by Django 6.0.3 on 2026-09-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20260923_1131'),
        ('api', '0027_subscription_pending_seat_quantity'),
    ]

    operations = [
    ]
