# Generated by Django 6.0.3 on 2026-09-29 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20260927_2257'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('icon_name', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'help categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('issue_category', models.CharField(choices=[('story_loading', 'Story loading'), ('audio_mic', 'Audio or microphone'), ('missing_badges', 'Missing badges'), ('account_setup', 'Account setup'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('audience', models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent'), ('learner', 'Learner'), ('general', 'General')], default='general', max_length=10)),
                ('content', models.TextField()),
                ('video_tutorial_url', models.URLField(blank=True)),
                ('is_kid_friendly', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='api.helpcategory')),
            ],
            options={
                'ordering': ('category__order', 'title'),
                'indexes': [models.Index(fields=['audience', 'category'], name='help_article_aud_cat_idx')],
            },
        ),
    ]
