# Generated by Django 6.0.3 on 2026-10-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_repair_grade4_story_activities'),
        ('api', '0038_expand_enterprise_funding_options'),
    ]

    operations = [
    ]
