# Generated by Django 6.1 on 2026-10-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_capitalize_sgila_in_help_faq'),
        ('api', '0039_merge_20261001_2310'),
    ]

    operations = [
    ]
