# Generated by Django 6.0.3 on 2026-10-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_number', models.CharField(help_text='DBE EMIS number. The stable identifier used to re-import updates.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('Northern Cape', 'Northern Cape'), ('North West', 'North West'), ('Western Cape', 'Western Cape')], max_length=64)),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('town', models.CharField(blank=True, default='', max_length=128)),
                ('township_village', models.CharField(blank=True, default='', max_length=128)),
                ('quintile', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Quintile 1'), (2, 'Quintile 2'), (3, 'Quintile 3'), (4, 'Quintile 4'), (5, 'Quintile 5')], help_text='DBE poverty ranking, 1 (poorest) to 5. Blank when unknown.', null=True)),
                ('sector', models.CharField(choices=[('public', 'Public'), ('independent', 'Independent'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending open', 'Pending open')], default='open', max_length=16)),
                ('school_type', models.CharField(blank=True, default='', max_length=64)),
                ('urban_rural', models.CharField(blank=True, default='', max_length=32)),
                ('learners_2025', models.PositiveIntegerField(blank=True, help_text='Learner enrolment as published for 2025.', null=True)),
            ],
            options={
                'verbose_name_plural': 'schools',
                'ordering': ['name', 'emis_number'],
                'indexes': [models.Index(fields=['province', 'name'], name='school_province_name_idx'), models.Index(fields=['name'], name='school_name_idx'), models.Index(fields=['province', 'status'], name='school_prov_status_idx')],
            },
        ),
    ]
